### ISSUE TITLE
"Something went wrong, unable to detect SQL details from registry"

### ISSUE THREAD

**Issue by 7MinSec** [nettitude/SharpWSUS#4]
Hello,

I'm trying to play with SharpWSUS in my lab before trying at a client site pentest.  I have WSUS deployed on a test server, and a GPO pushed out to all clients that hooks them to the WSUS server to get updates.  Whenever I run `SharpWSUS inspect` I get:

```
Something went wrong, unable to detect SQL details from registry
```
...followed by an unhandled SharpWSUS exception (I can send details if need be).  

I haven't admin'd WSUS for forever and a day.  So I'm wondering if this is an error that literally means I'm not using SQL, as if I'm understanding [this article](https://learn.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration) correctly, WSUS can use an internal database or be fully baked into SQL (which I haven't configured).

**Comment by 7MinSec** [comment]
I'm going to close for now.  I get this error whether I run on my WSUS server or a client.  I'm thinking this needs a SQL backend to run, but please let me know if I'm wrong.

**Comment by melid404** [comment]
This pull request fixes the issue:

https://github.com/nettitude/SharpWSUS/pull/2

**Comment by 7MinSec** [comment]
Thanks!
